# Generated by Django 4.0.3 on 2022-04-10 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationNotResidentialBuilding',
            fields=[
                ('calification', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('min_C', models.FloatField()),
                ('max_C', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ClassificationResidentialBuilding',
            fields=[
                ('calification', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('min_C1', models.FloatField()),
                ('max_C1', models.FloatField()),
                ('min_C2', models.FloatField(null=True)),
                ('max_C2', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExistingBuldingDemandDispersions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_type', models.BooleanField()),
                ('climatic_zone', models.CharField(max_length=4)),
                ('dispersion', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExistingBuldingEnergyAndEmissionsDispersions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_type', models.BooleanField()),
                ('climatic_zone', models.CharField(max_length=4)),
                ('dispersion', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewBuldingDemandDispersions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_type', models.BooleanField()),
                ('climatic_zone', models.CharField(max_length=4)),
                ('dispersion', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewBuldingEnergyAndEmissionsDispersions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_type', models.BooleanField()),
                ('climatic_zone', models.CharField(max_length=4)),
                ('dispersion', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NewBuildingEnergyConsume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_type', models.BooleanField()),
                ('climatic_zone', models.CharField(max_length=4)),
                ('heating_mean', models.FloatField()),
                ('refrigeration', models.FloatField()),
                ('ACS', models.FloatField()),
            ],
            options={
                'unique_together': {('building_type', 'climatic_zone')},
            },
        ),
        migrations.CreateModel(
            name='NewBuildingEmissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_type', models.BooleanField()),
                ('climatic_zone', models.CharField(max_length=4)),
                ('heating_mean', models.FloatField()),
                ('refrigeration', models.FloatField()),
                ('ACS', models.FloatField()),
            ],
            options={
                'unique_together': {('building_type', 'climatic_zone')},
            },
        ),
        migrations.CreateModel(
            name='NewBuildingDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_type', models.BooleanField()),
                ('climatic_zone', models.CharField(max_length=4)),
                ('heating_mean', models.FloatField()),
                ('refrigeration', models.FloatField()),
            ],
            options={
                'unique_together': {('building_type', 'climatic_zone')},
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.user')),
            ],
        ),
        migrations.CreateModel(
            name='ExistingBuildingEnergyConsume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_type', models.BooleanField()),
                ('climatic_zone', models.CharField(max_length=4)),
                ('heating_mean', models.FloatField()),
                ('refrigeration', models.FloatField()),
                ('ACS', models.FloatField()),
            ],
            options={
                'unique_together': {('building_type', 'climatic_zone')},
            },
        ),
        migrations.CreateModel(
            name='ExistingBuildingEmissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_type', models.BooleanField()),
                ('climatic_zone', models.CharField(max_length=4)),
                ('heating_mean', models.FloatField()),
                ('refrigeration', models.FloatField()),
                ('ACS', models.FloatField()),
            ],
            options={
                'unique_together': {('building_type', 'climatic_zone')},
            },
        ),
        migrations.CreateModel(
            name='ExistingBuildingDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_type', models.BooleanField()),
                ('climatic_zone', models.CharField(max_length=4)),
                ('heating_mean', models.FloatField()),
                ('refrigeration', models.FloatField()),
            ],
            options={
                'unique_together': {('building_type', 'climatic_zone')},
            },
        ),
        migrations.CreateModel(
            name='Calcul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('calification', models.CharField(max_length=100)),
                ('consumption', models.FloatField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.file')),
            ],
        ),
    ]
